---
fail_fast: false

repos:
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.7.3
    hooks:
      - id: editorconfig-checker
        name: Enforces .editorconfig style

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        name: Formats JavaScript, JSON, and YAML files using Prettier
        types_or: [javascript, json, yaml]

  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
        name: Formats CMake files

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.3
    hooks:
      - id: clang-format
        name: Formats C++ code
        types_or: [c++]

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.5.0
    hooks:
      - id: commitlint
        name: Checks commit message
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
